### ISSUE TITLE
Improve reliability

### ISSUE THREAD

**Issue by fabiosangregorio** [fabiosangregorio/telereddit#38]
The bot has some unexpected downtime (see #37), especially during deployment. Reliability needs to be improved.

**Comment by MasterCruelty** [comment]
I'm not sure 100% but it stopped working twice consecutively with this input: ```r/boltedon```

I hope it can help

**Comment by fabiosangregorio** [comment]
Thank you so much for the invaluable information @MasterCruelty. It was in fact a problem with a post of that subreddit!
Should be fixed now.

**Comment by MasterCruelty** [comment]
Happy to know that :)

**Comment by fabiosangregorio** [comment]
Deployment on Heroku (commit 6a6a59c49fffa01bf422a44b55fd1af9ec9edf03) fixes the issue.
